### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jnv** [czechitas/tvorim-web-1#4]
- [x] odstranit úvodní prázdné slidy, nahradit instrukcemi k ovládání prezentace
- [x] odstranit proměnlivé údaje, contenteditable nebo proměnné
- [x] howto pro lektory
  - [x] briefing se zástupkyní czechitas - pravidla aj. jsou ve slidech
  - [x] sponzoři kurzu
  - [x] lístečky + záložní alternativa
  - [x] nezkracovat přestávky, slidy jsou hinty 
- [x] ke slidu HTML poznámka devtools
- [x] vyhodit info o délce přestávek
- [ ] Countdown na přestávky (lepší lístečky?)
- [ ] Sjednotit termíny: jednodenní = workshop; dlouhodobý = kurz

Zatím do forku.

**Comment by benabraham** [comment]
ty prazdny slajdy maj duvod, lze si zkouset ze ovladani funguje aniz bys ukazoval slajdy predcasne, zvlast bylo fajn, kdyz jeden z prvnich slajdu bylo video se sponzorem

**Comment by jnv** [comment]
@benabraham Tomu rozumím, probíral jsem to s Honzou Pobořilem. Mám s tím tyto problémy:

- na slidech nic není, takže musíš stejně koukat na URL abys viděl, že funguje clicker
- je to na houby pokud s účastnicemi sdílím odkaz na prezentaci, protože mají pocit, že to nefunguje; řešením je posílat odkaz až na nějaký 3., 4. slide, ale to se do budoucna může změnit.

S Honzou jsme se shodli, že bychom na první slide dali instrukce k ovládání prezentace, na druhý posunuli ten úvod s instrukcemi pro připojení. To jsou slidy, které beztak chceš ukázat hned na začátku (čtenářce, resp. účastnicím).

**Comment by benabraham** [comment]
Jasně. Jinak prezentaci jsme naprosto záměrně dávali až po kurzu, protože předbíhaly (a často stejně špatně), ostatně na vyplnění času a udržení tempa pro všechny jsou tam bonusový úkoly.
A taky jen v podobě PDF, ta webová se právě musí učit ovládat.

Všechno, co potřebujou z výkladu (ze slajdů), aby je mohly dělat, je nově s úkolama v lístečkách.
